"""Add ownership to test_packages

Revision ID: 1bcbbed201db
Revises: ec2c3a5f4b9a
Create Date: 2025-10-27 19:24:22.810002+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcbbed201db'
down_revision: Union[str, Sequence[str], None] = 'ec2c3a5f4b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_packages', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_packages', 'admin_users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_packages', type_='foreignkey')
    op.drop_column('test_packages', 'owner_id')
    # ### end Alembic commands ###
