"""Add profile fields to admin_users

Revision ID: 1d47a0b32975
Revises: b925acb4901c
Create Date: 2025-10-11 21:39:10.096833+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d47a0b32975'
down_revision: Union[str, Sequence[str], None] = 'b925acb4901c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('admin_users', sa.Column('sipp_number', sa.String(length=50), nullable=True))
    op.add_column('admin_users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('admin_users', sa.Column('signature_image_url', sa.String(length=255), nullable=True))
    op.alter_column('package_tests', 'test_package_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('package_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('package_tests', 'test_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('subaspect_tests', 'sub_aspect_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('subaspect_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subaspect_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('subaspect_tests', 'sub_aspect_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('package_tests', 'test_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('package_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('package_tests', 'test_package_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('admin_users', 'signature_image_url')
    op.drop_column('admin_users', 'city')
    op.drop_column('admin_users', 'sipp_number')
    op.drop_column('admin_users', 'full_name')
    # ### end Alembic commands ###
