"""Add more details to participant

Revision ID: 1d621d74283f
Revises: 798bdbdb15c9
Create Date: 2025-10-07 07:07:02.615268+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d621d74283f'
down_revision: Union[str, Sequence[str], None] = '798bdbdb15c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.add_column('participants', sa.Column('job', sa.String(length=100), nullable=True))
    op.add_column('participants', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'address')
    op.drop_column('participants', 'job')
    op.drop_column('participants', 'registration_number')
    # ### end Alembic commands ###
