"""Add test_order to package_tests table

Revision ID: 4633d1fa0378
Revises: bafea05f44b4
Create Date: 2025-10-08 01:25:18.473748+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4633d1fa0378'
down_revision: Union[str, Sequence[str], None] = 'bafea05f44b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_tests', sa.Column('test_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_tests', 'test_order')
    # ### end Alembic commands ###
