"""Create initial schema from all current models

Revision ID: 798bdbdb15c9
Revises: 
Create Date: 2025-10-06 18:44:07.076911+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '798bdbdb15c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'test_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('sub_aspects', sa.Column('minimum_category', sa.String(length=10), server_default='B', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_aspects', 'minimum_category')
    op.alter_column('questions', 'text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('participants', 'test_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
