"""Change subaspect-test relationship to many-to-many

Revision ID: 89f6bffa9264
Revises: 1d621d74283f
Create Date: 2025-10-07 16:58:13.107955+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89f6bffa9264'
down_revision: Union[str, Sequence[str], None] = '1d621d74283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subaspect_tests',
    sa.Column('sub_aspect_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_aspect_id'], ['sub_aspects.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], )
    )
    op.drop_constraint(op.f('sub_aspects_ibfk_2'), 'sub_aspects', type_='foreignkey')
    op.drop_column('sub_aspects', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_aspects', sa.Column('test_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sub_aspects_ibfk_2'), 'sub_aspects', 'tests', ['test_id'], ['id'])
    op.drop_table('subaspect_tests')
    # ### end Alembic commands ###
