"""Add many-to-many relationship between templates and tests

Revision ID: b925acb4901c
Revises: 4633d1fa0378
Create Date: 2025-10-08 03:44:33.099287+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b925acb4901c'
down_revision: Union[str, Sequence[str], None] = '4633d1fa0378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package_tests', 'test_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('template_tests', sa.Column('psychogram_template_id', sa.Integer(), nullable=False))
    op.alter_column('template_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('template_tests_ibfk_1'), 'template_tests', type_='foreignkey')
    op.create_foreign_key(None, 'template_tests', 'psychogram_templates', ['psychogram_template_id'], ['id'])
    op.drop_column('template_tests', 'template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_tests', sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'template_tests', type_='foreignkey')
    op.create_foreign_key(op.f('template_tests_ibfk_1'), 'template_tests', 'psychogram_templates', ['template_id'], ['id'])
    op.alter_column('template_tests', 'test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('template_tests', 'psychogram_template_id')
    op.alter_column('package_tests', 'test_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
