"""Link interpretation rules to sub_aspects instead of tests

Revision ID: bafea05f44b4
Revises: 89f6bffa9264
Create Date: 2025-10-07 17:48:29.589386+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bafea05f44b4'
down_revision: Union[str, Sequence[str], None] = '89f6bffa9264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interpretation_rules', sa.Column('sub_aspect_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('interpretation_rules_ibfk_1'), 'interpretation_rules', type_='foreignkey')
    op.create_foreign_key(None, 'interpretation_rules', 'sub_aspects', ['sub_aspect_id'], ['id'])
    op.drop_column('interpretation_rules', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interpretation_rules', sa.Column('test_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interpretation_rules', type_='foreignkey')
    op.create_foreign_key(op.f('interpretation_rules_ibfk_1'), 'interpretation_rules', 'tests', ['test_id'], ['id'])
    op.drop_column('interpretation_rules', 'sub_aspect_id')
    # ### end Alembic commands ###
