"""Add parent_id hierarchy to admin_users

Revision ID: bbc08064d483
Revises: 1bcbbed201db
Create Date: 2025-10-27 20:20:38.221669+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc08064d483'
down_revision: Union[str, Sequence[str], None] = '1bcbbed201db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'admin_users', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'parent_id')
    # ### end Alembic commands ###
