"""Add role to admin_users table

Revision ID: ec2c3a5f4b9a
Revises: 1d47a0b32975
Create Date: 2025-10-12 20:36:47.483090+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2c3a5f4b9a'
down_revision: Union[str, Sequence[str], None] = '1d47a0b32975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('role', sa.String(length=50), server_default='admin', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'role')
    # ### end Alembic commands ###
